-- AUTO-GENERATED local-dev seed for the Supabase CLI stack.
-- Runs automatically on `supabase start` / `supabase db reset` (see [db.seed] in config.toml).
--
-- 1) Grants: the local stack's default privileges do NOT give anon/authenticated
--    SELECT/INSERT/UPDATE/DELETE on public tables (they only get TRUNCATE/REFERENCES/TRIGGER),
--    which the app + RLS policies assume. Re-grant them here (RLS still enforces row access).
-- 2) Reference data: scholarships / universities / professors, converted from scripts/data/*.json,
--    so search features have data without needing the SSL-only npm seed scripts locally.

grant select, insert, update, delete on all tables in schema public to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- Scholarships
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Australia Awards Scholarships', 'Australia', null, array['bsc', 'msc', 'phd'], '{}', 'fully_funded', 'Full tuition, living allowance, travel', '2026-04-30', 'Citizens of participating developing countries including Bangladesh. Minimum academic requirements apply.', 'https://www.dfat.gov.au/people-to-people/australia-awards');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Destination Australia Scholarship', 'Australia', null, array['bsc', 'msc'], '{}', 'partial', 'Up to AUD 15,000 per year', '2026-01-31', 'International students studying at regional Australian campuses.', 'https://www.education.gov.au/destination-australia');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('University of Melbourne Graduate Research Scholarships', 'Australia', 'University of Melbourne', array['msc', 'phd'], array['research'], 'fully_funded', 'Full fee remission + living stipend', '2026-10-31', 'High-achieving research students. Competitive GPA required.', 'https://study.unimelb.edu.au/how-to-apply/scholarships');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('ANU Chancellor''s International Scholarship', 'Australia', 'Australian National University', array['bsc', 'msc'], '{}', 'merit', '25–50% tuition reduction', null, 'International undergraduate and postgraduate coursework students.', 'https://www.anu.edu.au/study/scholarships');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('University of Adelaide Global Academic Excellence', 'Australia', 'University of Adelaide', array['bsc', 'msc'], '{}', 'merit', '50% tuition fee reduction', '2026-06-30', 'Minimum GPA equivalent 5.0/7.0 or higher.', 'https://international.adelaide.edu.au/admissions/scholarships');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Monash International Leadership Scholarship', 'Australia', 'Monash University', array['bsc', 'msc'], '{}', 'merit', 'AUD 10,000 per year', '2026-03-15', 'Outstanding international students commencing at Monash.', 'https://www.monash.edu/study/fees-scholarships/scholarships');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Chevening Scholarships', 'United Kingdom', null, array['msc'], '{}', 'fully_funded', 'Full tuition, living costs, flights', '2026-11-05', 'Leadership potential. 2+ years work experience. Bangladesh eligible.', 'https://www.chevening.org/scholarships/');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Commonwealth Shared Scholarships', 'United Kingdom', null, array['msc'], '{}', 'fully_funded', 'Full tuition and living allowance', '2026-12-13', 'Students from developing Commonwealth countries who cannot otherwise afford UK study.', 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships/');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Vanier Canada Graduate Scholarships', 'Canada', null, array['phd'], '{}', 'fully_funded', 'CAD 50,000 per year for 3 years', '2026-10-30', 'Doctoral students demonstrating research excellence and leadership.', 'https://vanier.gc.ca/en/home-accueil.html');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('University of Toronto Lester B. Pearson Scholarship', 'Canada', 'University of Toronto', array['bsc'], '{}', 'fully_funded', 'Full tuition, books, incidental fees, residence', '2026-11-15', 'International students entering undergraduate programs. Exceptional academic achievement.', 'https://future.utoronto.ca/pearson/about/');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Fulbright Foreign Student Program', 'United States', null, array['msc', 'phd'], '{}', 'fully_funded', 'Tuition, living stipend, health insurance', '2026-05-15', 'Bangladeshi citizens. Varies by field and university placement.', 'https://foreign.fulbrightonline.org/');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Cybersecurity MSc Scholarship — UNSW', 'Australia', 'UNSW Sydney', array['msc'], array['cybersecurity', 'computer science'], 'partial', 'AUD 20,000 tuition fee waiver', '2026-07-01', 'MSc in Cybersecurity or related IT field. IELTS 6.5+.', 'https://www.unsw.edu.au/research/hdr/scholarships');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('Ontario Graduate Scholarship', 'Canada', null, array['msc', 'phd'], '{}', 'merit', 'CAD 15,000 per year', '2026-02-01', 'Merit-based award for graduate study in Ontario.', 'https://www.ontario.ca/page/ontario-graduate-scholarship');
insert into public.scholarships (name, country, university, degree_levels, fields, funding_type, amount_description, deadline, eligibility, source_url) values ('DAAD EPOS Scholarships', 'Germany', null, array['msc'], array['development', 'engineering', 'computer science'], 'fully_funded', 'Monthly stipend, travel, insurance', '2026-07-31', 'Development-related master''s programs in Germany.', 'https://www.daad.de/en/study-and-research-in-germany/scholarships');

-- Universities
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('University of Melbourne', 'Australia', 'Melbourne', 'https://www.unimelb.edu.au', 28000, 42000, 3, 6.5, array['bsc', 'msc', 'phd'], array['computer science', 'cybersecurity', 'engineering']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('University of Adelaide', 'Australia', 'Adelaide', 'https://www.adelaide.edu.au', 25000, 38000, 2.8, 6.5, array['bsc', 'msc', 'phd'], array['cybersecurity', 'computer science', 'data science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('Monash University', 'Australia', 'Melbourne', 'https://www.monash.edu', 26000, 40000, 2.9, 6.5, array['bsc', 'msc', 'phd'], array['information technology', 'cybersecurity']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('UNSW Sydney', 'Australia', 'Sydney', 'https://www.unsw.edu.au', 30000, 45000, 3.1, 6.5, array['bsc', 'msc', 'phd'], array['cybersecurity', 'computer science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('Australian National University', 'Australia', 'Canberra', 'https://www.anu.edu.au', 27000, 41000, 3, 6.5, array['bsc', 'msc', 'phd'], array['computer science', 'engineering']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('University of Toronto', 'Canada', 'Toronto', 'https://www.utoronto.ca', 32000, 48000, 3.2, 6.5, array['bsc', 'msc', 'phd'], array['computer science', 'cybersecurity']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('University of British Columbia', 'Canada', 'Vancouver', 'https://www.ubc.ca', 30000, 44000, 3, 6.5, array['bsc', 'msc', 'phd'], array['computer science', 'data science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('University of Manchester', 'United Kingdom', 'Manchester', 'https://www.manchester.ac.uk', 28000, 42000, 3, 6.5, array['bsc', 'msc', 'phd'], array['cybersecurity', 'computer science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('University of Edinburgh', 'United Kingdom', 'Edinburgh', 'https://www.ed.ac.uk', 29000, 43000, 3.1, 6.5, array['msc', 'phd'], array['informatics', 'cybersecurity', 'artificial intelligence']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('Arizona State University', 'United States', 'Tempe', 'https://www.asu.edu', 25000, 38000, 2.7, 6, array['bsc', 'msc'], array['cybersecurity', 'computer science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('Georgia Institute of Technology', 'United States', 'Atlanta', 'https://www.gatech.edu', 35000, 52000, 3.3, 7, array['msc', 'phd'], array['cybersecurity', 'computer science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('Deakin University', 'Australia', 'Melbourne', 'https://www.deakin.edu.au', 20000, 30000, 2.5, 6, array['bsc', 'msc'], array['cybersecurity', 'information technology']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('University of Sydney', 'Australia', 'Sydney', 'https://www.sydney.edu.au', 32000, 48000, 3, 6.5, array['bsc', 'msc', 'phd'], array['computer science', 'cybersecurity', 'data science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('McGill University', 'Canada', 'Montreal', 'https://www.mcgill.ca', 18000, 35000, 3.2, 6.5, array['bsc', 'msc', 'phd'], array['computer science', 'engineering', 'data science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('University of Waterloo', 'Canada', 'Waterloo', 'https://uwaterloo.ca', 22000, 40000, 3.3, 6.5, array['bsc', 'msc', 'phd'], array['computer science', 'cybersecurity', 'software engineering']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('Imperial College London', 'United Kingdom', 'London', 'https://www.imperial.ac.uk', 38000, 55000, 3.4, 7, array['bsc', 'msc', 'phd'], array['computer science', 'cybersecurity', 'engineering']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('Technical University of Munich', 'Germany', 'Munich', 'https://www.tum.de', 0, 3000, 3, 6.5, array['bsc', 'msc', 'phd'], array['computer science', 'engineering', 'data science']);
insert into public.universities (name, country, city, website, tuition_usd_min, tuition_usd_max, min_gpa, min_ielts, degree_levels, fields) values ('MIT', 'United States', 'Cambridge', 'https://www.mit.edu', 55000, 60000, 3.7, 7, array['bsc', 'msc', 'phd'], array['computer science', 'artificial intelligence', 'cybersecurity']);

-- Professors (university_id resolved by university name)
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Sarah Chen', (select id from public.universities where name = 'University of Melbourne' limit 1), 'School of Computing and Information Systems', 's.chen@unimelb.edu.au', array['cybersecurity', 'network security', 'malware analysis'], 'https://www.unimelb.edu.au', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. James Okonkwo', (select id from public.universities where name = 'UNSW Sydney' limit 1), 'School of Computer Science and Engineering', 'j.okonkwo@unsw.edu.au', array['cybersecurity', 'cryptography', 'blockchain'], 'https://www.unsw.edu.au', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Priya Sharma', (select id from public.universities where name = 'University of Adelaide' limit 1), 'School of Computer Science', 'priya.sharma@adelaide.edu.au', array['data science', 'machine learning', 'computer science'], 'https://www.adelaide.edu.au', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. Michael Torres', (select id from public.universities where name = 'Monash University' limit 1), 'Faculty of Information Technology', 'm.torres@monash.edu', array['information technology', 'cybersecurity', 'cloud security'], 'https://www.monash.edu', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Emily Watson', (select id from public.universities where name = 'University of Toronto' limit 1), 'Department of Computer Science', 'ewatson@cs.toronto.edu', array['computer science', 'artificial intelligence', 'nlp'], 'https://www.utoronto.ca', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. David Kim', (select id from public.universities where name = 'University of British Columbia' limit 1), 'Department of Electrical and Computer Engineering', 'dkim@ece.ubc.ca', array['engineering', 'computer science', 'embedded systems'], 'https://www.ubc.ca', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Rachel Green', (select id from public.universities where name = 'University of Manchester' limit 1), 'Department of Computer Science', 'rachel.green@manchester.ac.uk', array['cybersecurity', 'privacy', 'computer science'], 'https://www.manchester.ac.uk', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. Oliver Hughes', (select id from public.universities where name = 'University of Edinburgh' limit 1), 'School of Informatics', 'o.hughes@ed.ac.uk', array['data science', 'machine learning', 'computer science'], 'https://www.ed.ac.uk', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Anna Petrov', (select id from public.universities where name = 'Georgia Institute of Technology' limit 1), 'School of Cybersecurity and Privacy', 'apetrov@gatech.edu', array['cybersecurity', 'network security', 'iot security'], 'https://www.gatech.edu', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. Robert Lee', (select id from public.universities where name = 'Carnegie Mellon University' limit 1), 'School of Computer Science', 'rlee@cmu.edu', array['cybersecurity', 'software engineering', 'computer science'], 'https://www.cmu.edu', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Fatima Al-Rashid', (select id from public.universities where name = 'University of Melbourne' limit 1), 'School of Computing and Information Systems', 'f.alrashid@unimelb.edu.au', array['data science', 'health informatics', 'computer science'], 'https://www.unimelb.edu.au', true, false);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. Thomas Wright', (select id from public.universities where name = 'University of Toronto' limit 1), 'Department of Computer Science', 'twright@cs.toronto.edu', array['computer science', 'distributed systems', 'cloud computing'], 'https://www.utoronto.ca', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Lisa Nguyen', (select id from public.universities where name = 'University of Sydney' limit 1), 'School of Computer Science', 'lisa.nguyen@sydney.edu.au', array['cybersecurity', 'network security', 'data science'], 'https://www.sydney.edu.au', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. Ahmed Hassan', (select id from public.universities where name = 'McGill University' limit 1), 'School of Computer Science', 'ahmed.hassan@mcgill.ca', array['machine learning', 'computer science', 'nlp'], 'https://www.mcgill.ca', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Sophie Martin', (select id from public.universities where name = 'University of Waterloo' limit 1), 'Cheriton School of Computer Science', 'sophie.martin@uwaterloo.ca', array['cybersecurity', 'software engineering', 'privacy'], 'https://uwaterloo.ca', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. Daniel Clarke', (select id from public.universities where name = 'Imperial College London' limit 1), 'Department of Computing', 'd.clarke@imperial.ac.uk', array['cybersecurity', 'distributed systems', 'computer science'], 'https://www.imperial.ac.uk', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Dr. Hans Weber', (select id from public.universities where name = 'Technical University of Munich' limit 1), 'Department of Informatics', 'h.weber@tum.de', array['data science', 'engineering', 'computer science'], 'https://www.tum.de', true, true);
insert into public.professors (name, university_id, department, email, research_areas, website, accepts_msc, accepts_phd) values ('Prof. Maria Santos', (select id from public.universities where name = 'MIT' limit 1), 'EECS', 'msantos@mit.edu', array['artificial intelligence', 'computer science', 'cybersecurity'], 'https://www.mit.edu', true, true);
