import type { Profile } from "@/types/database";

export type SopInputs = {
  motivation: string;
  experience: string;
  goals: string;
  whyNow: string;
};

export function generateSopDraft(profile: Profile, inputs: SopInputs) {
  const degree =
    profile.degree_level === "phd"
      ? "doctoral"
      : profile.degree_level === "msc"
        ? "master's"
        : "graduate";

  return `# Statement of Purpose — ${profile.full_name}

## Introduction
I am applying for a ${degree} program in ${profile.field_of_study}, building on my academic foundation from ${profile.home_country} where I achieved a CGPA of ${profile.cgpa ?? "[CGPA]"}.${profile.ielts_score ? ` I have demonstrated English proficiency with an IELTS score of ${profile.ielts_score}.` : ""}

${inputs.motivation.trim() || "[Describe what sparked your interest in this field and why it matters to you.]"}

## Academic & professional background
${inputs.experience.trim() || "[Summarize relevant coursework, projects, internships, and research experience. Be specific about outcomes and skills gained.]"}

## Research / career goals
${inputs.goals.trim() || `[Explain what you hope to study during your ${degree} program and how it connects to your long-term career.]`}

## Why now
${inputs.whyNow.trim() || "[Why is this the right time for you to pursue this degree abroad?]"}

## Why these destinations
I am particularly interested in studying in ${profile.preferred_countries.join(" or ")}, where I can access strong programs in ${profile.field_of_study}${profile.budget_usd ? ` within a budget of approximately $${profile.budget_usd.toLocaleString()} per year` : ""}.

## Conclusion
I am eager to contribute to ${profile.field_of_study} through rigorous study and research. I am confident that my preparation and motivation make me a strong candidate, and I look forward to the opportunity to grow in an international academic environment.

---
*Draft generated by ScholarGenie AI — edit every section in your own voice before submitting.*`;
}
